@startuml States
[*] --> Запуск_программы : Инициация запуска
Запуск_программы --> Ошибка_запуска : Ошибка запуска
Запуск_программы --> Ожидание_задачи : Подгрузка задач
Ожидание_задачи --> Выбор_задачи : Задача подгружена
Выбор_задачи --> Ожидание_участников : Подгрузка участников
Ожидание_участников --> Выбор_участника : Участники подгружены
Выбор_участника --> Опрос_участника : Начать опрос участника

Опрос_участника --> Готов : Участник готов
Опрос_участника --> Отказ : Участник отказался
Опрос_участника --> Спросить_позже : Участник попросил спросить позже

Готов --> Выбор_задачи : Задача завершена
Отказ --> Ожидание_участников : Выбор следующего участника
Спросить_позже --> Ожидание_участников : Выбор следующего участника

Ожидание_участников --> Завершение_опроса : Все участники опрошены

Ожидание_задачи --> [*] : Задачи отсутствуют
Завершение_опроса --> [*]
Ошибка_запуска --> [*]

@enduml
